# Generated by Django 4.2.1 on 2023-05-13 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_date_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(
                max_length=5000,
                validators=[django.core.validators.MinLengthValidator(100)],
            ),
        ),
    ]
