# Generated by Django 4.2.1 on 2023-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
